-- frontend/supabase/migrations/2025xxxxxx_create_base_schema.sql (全文)

-- =======================================================
-- 1. クライアントテーブル (clients)
-- =======================================================
CREATE TABLE public.clients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE NOT NULL
);

-- RLS: clientsの読み取りを認証なしで許可 (匿名アクセス)
CREATE POLICY "Allow public read access to clients"
ON public.clients 
FOR SELECT
USING (true);

-- =======================================================
-- 2. プロジェクトテーブル (projects)
-- =======================================================
CREATE TABLE public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  status TEXT DEFAULT '未着手' NOT NULL,
  -- 外部キー: clients.id と紐付け
  client_id BIGINT REFERENCES public.clients(id) ON DELETE SET NULL
);

-- RLS: projectsの読み取りを認証なしで許可
CREATE POLICY "Allow public read access to projects"
ON public.projects 
FOR SELECT
USING (true);

-- RLS: projectsの挿入を認証済みユーザーに許可 (CreateProjectModal用)
CREATE POLICY "Allow authenticated insert to projects"
ON public.projects 
FOR INSERT
TO authenticated
WITH CHECK (true);

-- =======================================================
-- 3. タスクテーブル (tasks)
-- =======================================================
CREATE TABLE public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  name TEXT NOT NULL,
  status TEXT DEFAULT '未着手' NOT NULL,
  due_date DATE,
  -- 外部キー: projects.id と紐付け (プロジェクト削除時にタスクも連動削除)
  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE
);

-- RLS: tasksの読み取りを認証なしで許可
CREATE POLICY "Allow public read access to tasks"
ON public.tasks 
FOR SELECT
USING (true);

-- RLS: tasksの挿入を認証済みユーザーに許可 (CreateTaskModal用)
CREATE POLICY "Allow authenticated insert to tasks"
ON public.tasks 
FOR INSERT
TO authenticated
WITH CHECK (true);
