-- supabase/migrations/2025xxxxxx_create_meetings_table.sql (全文)

-- =======================================================
-- 1. 議事録テーブル (meetings)
-- =======================================================
CREATE TABLE public.meetings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  date DATE NOT NULL,
  file_url TEXT,
  summary TEXT,
  -- 外部キー: clients.id と紐付け
  client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE
);

-- RLS: meetingsの読み取りを認証なしで許可
CREATE POLICY "Allow public read access to meetings"
ON public.meetings 
FOR SELECT
USING (true);

-- RLS: meetingsの挿入を認証済みユーザーに許可 (新規登録用)
CREATE POLICY "Allow authenticated insert to meetings"
ON public.meetings 
FOR INSERT
TO authenticated
WITH CHECK (true);
